version: '2.2'

services:

  rif-mysql:
    container_name: rif-mysql
    image: mysql:8.0
    environment:
      - MYSQL_USER=notifier_user
      - MYSQL_PASSWORD=${dbuserpassword}
      - MYSQL_ROOT_PASSWORD=${dbrootpassword}
      - MYSQL_DATABASE=rif_notifier
    ports:
      - 3308:3306
    networks:
      - rif-notifier-network
    healthcheck:
      test: ["CMD", "mysqladmin" , "--user", "root", "--password=${dbrootpassword}", "ping", "-h", "localhost"]
      timeout: 120s
      retries: 10


  regtest:
    container_name: regtest
    image: rsksmart/rskj-standalone:latest
    networks:
      - rif-notifier-network

  rif-notifier:
    container_name: rif-notifier
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - rif-mysql
      - regtest
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - rif-notifier-network

networks:
  rif-notifier-network:
