logging:
    level:
        org:
            rif:
                notifier:
                    datafetcher: ERROR
                    scheduled: ERROR
                    scheduled.NotificationProcessorJob: ERROR
notificationservice:
    email:
        from: no_reply@iovlabs.org
        smtppassword: ''
        smtpserver: ''
        smtpuser: ''
    integrationtest:
        apiendpoint: https://postman-echo.com/post
        apiendpoint.apikey: integrationtest
        apiendpoint.password: ''
        apiendpoint.user: integrationtest
        emaildestination: krishnalasdev@gmail.com
        smsdestination: 19175245555
        user: integrationtestuser
        user.apikey: integrationtest
    maxretries: 3
    services:
        enabled: API,EMAIL
    sms:
        from: 13473475555
    twilio:
        account_sid: test
        auth_token: test
notifier:
    blocks:
        startFromLast: false
    notifications:
        maxquerylimit: 1000
    run:
        fixedDelayFetchingChainAddresses: 3000
        fixedDelayFetchingJob: 5000
        fixedDelayNotificationJob: 3600000
        fixedDelayProcessJob: 3000
        fixedInitialDelayFetchingChainAddresses: 2000
        fixedInitialDelayFetchingJob: 2000
        fixedInitialDelayNotificationJob: 3600000
        fixedInitialDelayProcessJob: 2000
rif:
    notifier:
        account:
            file: UTC--2019-04-19T15-07-00.568000000Z--034000b5f2862d114e4b3474f79fc64aad0cb742.json
            paassword: Z&VT=JRSAQAsMYgSXaCEMf!S7vXaDPfY+SW^aGC4TCATUTjExDb2+=GC7+fux88LdGtR!^m-v4dtX2_*2?9@E$7B7f!RCExn&4R9$GMHxK5vrk&qrp8aZ5Z4GzWPP5@vnffKpXU*2evJm!GtDCN-@BWZ-V*6EMeQ*3Rc=y-gbWFUGGm4+7y2j3fs@mxT$kSe48as-aTZ?BdtMUNgH4tJzeF2%hsy5$M@ELY86Z9dfLWWjq!Up-atxPr!Wt&3a2LZ
        provider:
            address: '0x882bf23c4a7E73cA96AF14CACfA2CC006F6781A9'
            privatekey: a392604efc2fad9c0b3da43b5f698a2e3f270f170d859912be0d54742275c5f6
rsk:
    blockchain:
        endpoint: http://localhost:7545
        multichaincontract: '0xFEC354973ca22697BC5Cd1E7F372609574e2AfcA'
        tokennetworkregistry: '0xFEC354973ca22697BC5Cd1E7F372609574e2AfcA'
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rif_notifier?createDatabaseIfNotExist=true
        initialization-mode: never
        username: root
        password: root
    mail:
        host: smtp.gmail.com
        password: password
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
        username: username
flyway:
    url: jdbc:mysql:${dbhost:localhost}/${dbname:rif_notifier}
    user: ${dbuser:root}
    password: ${dbpassword:root}