logging:
    level:
        org:
            rif:
                notifier:
                    datafetcher: ERROR
                    scheduled: ERROR
                    scheduled.NotificationProcessorJob: ERROR
notificationservice:
    email:
        from: no_reply@iovlabs.org
        smtppassword:
        smtpserver:
        smtpuser:
    integrationtest:
        apiendpoint: https://postman-echo.com/post
        apiendpoint.apikey: integrationtest
        apiendpoint.password:
        apiendpoint.user: integrationtest
        emaildestination: test@do-not-reply-test.com
        smsdestination: 19175245555
        user: integrationtestuser
        user.apikey: integrationtest
    maxretries: 3
    services:
        enabled: API
    sms:
        from: 13473475555
    twilio:
        account_sid: test
        auth_token: test
notifier:
    blocks:
        startFromLast: false
    notifications:
        maxquerylimit: 1000
    run:
        fixedDelayFetchingChainAddresses: 3000
        fixedDelayFetchingJob: 5000
        fixedDelayNotificationJob: 3600000
        fixedDelayProcessJob: 3000
        fixedInitialDelayFetchingChainAddresses: 2000
        fixedInitialDelayFetchingJob: 2000
        fixedInitialDelayNotificationJob: 3600000
        fixedInitialDelayProcessJob: 2000
    endpoints:
        subscribecontroller: true
rif:
    notifier:
        account:
            file: UTC--2019-04-19T15-07-00.568000000Z--034000b5f2862d114e4b3474f79fc64aad0cb742.json
            password:
        provider:
            address: ${provideraddress}
            privatekey: ${providerprivatekey}
rsk:
    blockchain:
        endpoint: ${rskendpoint}
        multichaincontract: ${multichaincontract}
        tokennetworkregistry: ${tokennetworkregistry}
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rif_notifier?createDatabaseIfNotExist=true
        initialization-mode: never
        username: ${dbuser}
        password: ${dbpassword}
    mail:
        host: smtp.gmail.com
        password:
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
        username: username
flyway:
    url: jdbc:mysql:${dbhost:localhost}/${dbname:rif_notifier}
    user: ${dbuser}
    password: ${dbpassword}